on:
  pull_request_target:
    types:
      - ready_for_review
      - opened
      - synchronize
      - reopened
      - labeled
jobs:
  should-run:
    name: Should Run Preview Environment Provisioning?
    runs-on: ubuntu-latest
    if: |
      always() && 
      (
          (github.event.action == 'labeled' && github.event.label.name == 'env:withPreview') ||
          (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'env:with_preview')) ||
          (github.event_name == 'workflow_dispatch')
      )
    outputs:
      should-run: ${{ steps.changed-files.outputs.any_changed == "true" }}
    steps:
      - name: Print variables
        id: print_variables
        run: |
          echo "dupa"
  test:
    needs: should-run
    name: "Test job"
    runs-on: ubuntu-latest
    steps:
      - name: Print variables 2 
        id: print_variables_2
        run: |
          echo "2"
          echo "${{needs.should-run.outputs.should-run}}"
          
